[project]
name = "graph"
version = "0.1.0"
description = "TBD"
authors = [
    {name = "Kristoffer Andersson", email = "kristoffer.andersson@gu.se"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
